// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.org.intersect.dms.webapp.controller;

import java.io.Serializable;

privileged aspect LocationConnectForm_Roo_Serializable {
    
    declare parents: LocationConnectForm implements Serializable;
    
    private static final long LocationConnectForm.serialVersionUID = 1L;
    
}
