// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.org.intersect.dms.bookinggw.domain;

import java.io.Serializable;

privileged aspect AgsUsersBookingsPK_Roo_Serializable {
    
    declare parents: AgsUsersBookingsPK implements Serializable;
    
    private static final long AgsUsersBookingsPK.serialVersionUID = 1L;
    
}
