// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.org.intersect.dms.bookinggw.domain;

import java.lang.Integer;

privileged aspect Participants_Roo_JavaBean {
    
    public Integer Participants.getAgsUsers() {
        return this.agsUsers;
    }
    
    public void Participants.setAgsUsers(Integer agsUsers) {
        this.agsUsers = agsUsers;
    }
    
}
