#!/bin/bash
# chkconfig: 234 20 80
# description: Tomcat Server basic start/shutdown script
# processname: tomcat
JAVA_HOME="_JAVA_HOME_"
export JAVA_HOME
export JAVA_OPTS="-XX:MaxPermSize=368M -Xmx712M"
TOMCAT_HOME="_TOMCAT_HOME_"
START_TOMCAT=$TOMCAT_HOME/bin/startup.sh
STOP_TOMCAT=$TOMCAT_HOME/bin/shutdown.sh
start() {
echo -n "Starting tomcat: "
cd $TOMCAT_HOME
su -c ${START_TOMCAT} _DMS_USER_
echo "done."
}
stop() {
echo -n "Shutting down tomcat: "
cd $TOMCAT_HOME
su -c ${STOP_TOMCAT} _DMS_USER_
echo "done."
}
case "$1" in
start)
start
;;
stop)
stop
;;
restart)
stop
sleep 10
start
;;
*)
echo "Usage: $0 {start|stop|restart}"
esac
exit 0

