// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.org.intersect.dms.core.service.dto;

import java.io.Serializable;

privileged aspect CreateDirectoryParameter_Roo_Serializable {
    
    declare parents: CreateDirectoryParameter implements Serializable;
    
    private static final long CreateDirectoryParameter.serialVersionUID = 1L;
    
}
