// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.org.intersect.dms.core.service.dto;

import java.io.Serializable;

privileged aspect RenameParameter_Roo_Serializable {
    
    declare parents: RenameParameter implements Serializable;
    
    private static final long RenameParameter.serialVersionUID = 1L;
    
}
