// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.org.intersect.dms.core.domain;

privileged aspect FileInfo_Roo_Serializable {
    
    private static final long FileInfo.serialVersionUID = 1L;
    
}
